//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int uid { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string contactNo { get; set; }
        public string password { get; set; }
        public string accountType { get; set; }
    }
}
