//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventTicket
    {
        public int eventCode { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string description { get; set; }
        public int quantity { get; set; }
        public string eventname { get; set; }
        public System.DateTime publishTime { get; set; }
        public string eventType { get; set; }
        public string location { get; set; }
        public string imageName { get; set; }
        public string ballotOption { get; set; }
        public string recurring { get; set; }
    }
}
