//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int ratingID { get; set; }
        public string eventCode { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime time { get; set; }
        public int uid { get; set; }
        public string comment { get; set; }
        public string rating1 { get; set; }
    }
}
